DROP VIEW IF EXISTS cleaned_locations CASCADE;

CREATE VIEW cleaned_locations AS
SELECT *,
CASE
	WHEN user_location ILIKE '%Brazil%' 
          OR user_location ILIKE '%Brasil%'
	  OR user_location ILIKE '%Rio de%' THEN 'Brazil'
	WHEN user_location ILIKE '%United States%' 
	  OR user_location ILIKE '%USA%' 
	  OR user_location ILIKE '%America%' AND NOT user_location SIMILAR TO '%(North|South) America%'
          OR user_location ILIKE '%Alabama%'
          OR user_location ILIKE '%Alaska%'
          OR user_location ILIKE '%Arizona%'
          OR user_location ILIKE '%Arkansas%'
          OR user_location ILIKE '%California%'
          OR user_location ILIKE '%Colorado%'
          OR user_location ILIKE '%Connecticut%'
          OR user_location ILIKE '%Delaware%'
          OR user_location ILIKE '%Florida%'
          OR user_location ILIKE '%Georgia%'
          OR user_location ILIKE '%Hawaii%'
          OR user_location ILIKE '%Idaho%'
          OR user_location ILIKE '%Illinois%'
          OR user_location ILIKE '%Indiana%'
          OR user_location ILIKE '%Iowa%'
          OR user_location ILIKE '%Kansas%'
          OR user_location ILIKE '%Kentucky%'
          OR user_location ILIKE '%Louisiana%'
          OR user_location ILIKE '%Maine%'
          OR user_location ILIKE '%Maryland%'
          OR user_location ILIKE '%Massachusetts%'
          OR user_location ILIKE '%Michigan%'
          OR user_location ILIKE '%Minnesota%'
          OR user_location ILIKE '%Mississippi%'
          OR user_location ILIKE '%Missouri%'
          OR user_location ILIKE '%Montana%'
          OR user_location ILIKE '%Nebraska%'
          OR user_location ILIKE '%Nevada%'
          OR user_location ILIKE '%New Hampshire%'
          OR user_location ILIKE '%New Jersey%'
          OR user_location ILIKE '%New Mexico%'
          OR user_location ILIKE '%New York%'
          OR user_location ILIKE '%North Carolina%'
          OR user_location ILIKE '%North Dakota%'
          OR user_location ILIKE '%Ohio%'
          OR user_location ILIKE '%Oklahoma%'
          OR user_location ILIKE '%Oregon%'
          OR user_location ILIKE '%Pennsylvania%'
          OR user_location ILIKE '%Rhode Island%'
          OR user_location ILIKE '%South Carolina%'
          OR user_location ILIKE '%South Dakota%'
          OR user_location ILIKE '%Tennessee%'
          OR user_location ILIKE '%Texas%'
          OR user_location ILIKE '%Utah%'
          OR user_location ILIKE '%Vermont%'
          OR user_location ILIKE '%Virginia%'
          OR user_location ILIKE '%Washington%'
          OR user_location ILIKE '%West Virginia%'
          OR user_location ILIKE '%Wisconsin%'
	  OR user_location ILIKE '%Wyoming%' THEN 'United States'
	WHEN user_location ILIKE '%England%'
          OR user_location SIMILAR TO '%( |,)UK( %|,|$)'
          OR user_location ILIKE '%London%'
          OR user_location ILIKE '%United Kingdom%'
          OR user_location ILIKE '%Britain%' THEN 'United Kingdom'
	WHEN user_location ILIKE '%Germany%'
          OR user_location ILIKE '%Deutschland%'
          OR user_location ILIKE '%Berlin%' THEN 'Germany'
	WHEN user_location ILIKE '%Poland%'
          OR user_location ILIKE '%Polska%'
          OR user_location ILIKE '%Warsaw%' THEN 'Poland'
	WHEN user_location ILIKE '%Russia%'
          OR user_location ILIKE '%россия%'
          OR user_location ILIKE '%Moscow%'
          OR user_location ILIKE '%Москва%' THEN 'Russia'
END AS cleaned_location
FROM user_info;

DROP VIEW IF EXISTS cleaned_locations_trimmed;

CREATE VIEW cleaned_locations_trimmed AS
SELECT * FROM cleaned_locations
WHERE days_watched > 0 AND cleaned_location IS NOT NULL;

